### ISSUE TITLE
Code style is not java code convention

### ISSUE THREAD

**Issue by gitlabbin** [matt-mangia/kafka-admin#21]
ClassName should be written in UpperCamelCase.

such as google java code style
https://google.github.io/styleguide/javaguide.html

**Comment by matt-mangia** [comment]
@gitlabbin Thank you for catching this -- the project was originally a quick development to solve an immediate challenge and somehow this bad convention was held onto. Let me know if you see other style issues or feel free to put in a PR as well. Thanks!

**Comment by matt-mangia** [comment]
Change tested & merged, closing issue. Thank you!
